---
title: "Lab5"
author: "Dion, Julie, Mia, Vincent"
date: "9/13/2019"
output: 
    prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1
*Consider logistic regression with target as the outcome. Perform backward elimination based on p-values using a significance level of 0.001 to obtain a parsimonious model for the presence of heart disease.*

# Exercise 2
*Interpret the coefficient with the smallest p-value in the final model fit from Exercise 1. Make sure your interpretation is in context and explains the respective predictor.*


# Exercise 3
*Create a side-by-side box plot of the predicted probabilities from your final model from Exercise 1 split out by whether the person had heart disease or not. What does this plot suggest about how well this model can determine whether someone has heart disease?*


# Exercise 4
*Repeat Exercise 1 but now with forward selection rather than backward elimination. Again use a significance level of 0.001.*


# Exercise 5
*Are your final models from Exercises 1 and 3 the same? Are the final models from forward selection and backward elimination always the same? Please explain.*
